Samples/ViewComponentExample/Models/ErrorViewModel.cs
using System;

namespace ViewComponentExample.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Samples/ViewComponentExample/Models/NewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ViewComponentExample.Models
{
    public class NewModel
    {
        public string Title { get; set; }
        public string Sapo { get; set; }
        public string Image { get; set; }
    }
}

Samples/ViewComponentExample/Components/CallAjaxViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ViewComponentExample.Models;

namespace ViewComponentExample.Components
{
    public class CallAjaxViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Samples/ViewComponentExample/Components/PopularNewsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ViewComponentExample.Models;

namespace ViewComponentExample.Components
{
    public class PopularNewsViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            List<NewModel> newModels = new List<NewModel>();
            for (int i = 1; i <= 12; i++)
            {
                newModels.Add(new NewModel()
                {
                    Title = string.Format("This is title of article {0}", i),
                    Image = string.Format("../images/{0}.jpg", i)
                });
            }
            return View(newModels);
        }
    }
}

Samples/ViewComponentExample/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ViewComponentExample.Models;

namespace ViewComponentExample.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetTopMessage()
        {
            return ViewComponent("CallAjax", new { id = 1 });
        }

       
    }
}

Samples/ViewComponentExample/Views/Home/Components/CallAjax/Default.cshtml
<h3>I am a view component and called by ajax</h3>

Samples/ViewComponentExample/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome Home Page</h1>
</div>

<div class="view-component">
    @await Component.InvokeAsync("PopularNews")
</div>

<div class="view-component-ajax">
    <button type="button" id="btnCallAjax"> Click to call view component</button>
    <div class="content">

    </div>
</div>

@section Scripts{ 

<script>
    $(document).ready(function () {
        $("#btnCallAjax").click(function () {
            $.ajax({
                url: "../Home/GetTopMessage",
                type: "get",
                dataType: "html",
                beforeSend: function (x) {
                },
                data: null,
                success: function (result) {
                    $(".view-component-ajax .content").html(result);
                }
            });
        });
    });
</script>

}

Samples/ViewComponentExample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ViewComponentExample</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ViewComponentExample</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ViewComponentExample - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>